Enable KubeAPIServer --request-timeout flag
kubernetes/kops pull request #10038
Opened 2020-10-10 13:37 UTC by dntosas

In this PR, we initialize the support of `--request-timeout` flag on the configuration of KubeAPIServer so as to enable users for setting timeout value for all kinds of handlers.

Addresses https://github.com/kubernetes/kops/issues/10026

2020-10-10 13:49 UTC, dntosas commented
/retest-cla

2020-10-11 03:38 UTC, hakman requested changes
Thanks for adding this @dntosas. Should be a pretty useful option.
I added a few comments, mostly nits.
/ok-to-test

2020-10-11 03:38 UTC, hakman commented on pkg/apis/kops/componentconfig.go
> +	// RequestTimeout configures the minimum number of seconds a handler must keep a request open before timing it out.
```suggestion
	// RequestTimeout configures the duration a handler must keep a request open before timing it out. (default 1m0s)
```

2020-10-11 03:38 UTC, hakman commented on pkg/apis/kops/v1alpha2/componentconfig.go
> +	// RequestTimeout configures the minimum number of seconds a handler must keep a request open before timing it out.
```suggestion
	// RequestTimeout configures the duration a handler must keep a request open before timing it out. (default 1m0s)
```

2020-10-11 03:38 UTC, hakman commented on docs/cluster_spec.md
> +    requestTimeout: 0h3m0s
```suggestion
    requestTimeout: 3m0s
```

2020-10-11 03:38 UTC, hakman commented on docs/cluster_spec.md
> +The minimum number of seconds a handler must keep a request open before timing it out. Note that you must fill empty units of time with zeros. (default 1m0s)
```suggestion
The duration a handler must keep a request open before timing it out and can be overridden by other flags for specific types of requests.
Note that you must fill empty units of time with zeros.
```

2020-10-11 03:38 UTC, hakman commented on docs/cluster_spec.md
> +### Request Timeout
```suggestion
### Request Timeout
{{ kops_feature_table(kops_added_default='1.19') }}
```

2020-10-11 11:18 UTC, dntosas commented on docs/cluster_spec.md
> +### Request Timeout
commited ^

2020-10-11 11:18 UTC, dntosas commented on docs/cluster_spec.md
> +The minimum number of seconds a handler must keep a request open before timing it out. Note that you must fill empty units of time with zeros. (default 1m0s)
commited ^

2020-10-11 11:18 UTC, dntosas commented on docs/cluster_spec.md
> +    requestTimeout: 0h3m0s
commited ^

2020-10-11 11:18 UTC, dntosas commented on pkg/apis/kops/v1alpha2/componentconfig.go
> +	// RequestTimeout configures the minimum number of seconds a handler must keep a request open before timing it out.
commited ^

2020-10-11 11:18 UTC, dntosas commented on pkg/apis/kops/componentconfig.go
> +	// RequestTimeout configures the minimum number of seconds a handler must keep a request open before timing it out.
commited ^

2020-10-11 11:34 UTC, hakman commented
Thanks @dntosas !
/lgtm
/approve

2020-10-11 11:36 UTC, dntosas commented
> Thanks for adding this @dntosas. Should be a pretty useful option.
> I added a few comments, mostly nits.
> /ok-to-test

thanks for the comments @hakman !

qq: i made appropriate changes, and then tried a manual testing by cherry-picking this commit on `release-1.18` branch and build kops binary from there. what observed, is that although kops does actually update `cluster.yaml` on remote state, api-server still starts with default value of `request-timeour` rather than specified one ^^ maybe we miss something in this commit that prevent actual mapping from happening? still searching for this

2020-10-11 11:54 UTC, merged

2020-10-11 12:23 UTC, hakman commented
@dntosas for this to work you need a full build, including nodeup.

If you want cherrypick to 1.18, please do it using the ckerry-pick script from the kubernetes repo. If you do it soon it may be included in next build.