Setup a second NLB listener when an AWS ACM certificate is used
kubernetes/kops pull request #10157
Opened 2020-11-02 18:39 UTC by rifelpet

This uses commits from https://github.com/kubernetes/kops/pull/9761 combined with the new NLB support to provision a second NLB listener. It requires converting the `Listeners` and `TargetGroups` NLB fields to slices in which each listener should forward traffic to the target group of the same list index. I couldn't use a map of port number to TargetGroup because fi/loader.go uses reflection to set values of fields that are Tasks, and map values aren't addressable which resulted in a panic.

I also temporarily pulled in the commit from https://github.com/kubernetes/kops/pull/10076/files to run the e2e presubmit job with an ACM cert. Before we merge this I'll remove the commit.

2020-11-03 17:26 UTC, rifelpet commented
/test pull-kops-e2e-kubernetes-aws

2020-11-03 17:31 UTC, rifelpet commented
/test pull-kops-e2e-kubernetes-aws

2020-11-03 17:49 UTC, rifelpet commented
/test pull-kops-e2e-kubernetes-aws

2020-11-03 18:12 UTC, rifelpet commented
/test pull-kops-e2e-kubernetes-aws

2020-11-03 18:17 UTC, rifelpet commented
/test pull-kops-e2e-kubernetes-aws

2020-11-03 21:23 UTC, rifelpet commented
/test pull-kops-e2e-kubernetes-aws

2020-11-04 02:36 UTC, rifelpet commented
/test pull-kops-e2e-kubernetes-aws

2020-11-04 03:13 UTC, rifelpet commented
/test pull-kops-e2e-kubernetes-aws

2020-11-04 04:42 UTC, rifelpet commented
/test pull-kops-e2e-kubernetes-aws

2020-11-04 13:18 UTC, rifelpet commented
/test pull-kops-e2e-kubernetes-aws

2020-11-04 13:21 UTC, rifelpet commented
/test pull-kops-e2e-kubernetes-aws

2020-11-06 18:03 UTC, rifelpet commented
/hold for https://github.com/kubernetes/kops/pull/10156

2020-11-08 05:17 UTC, hakman commented
/test pull-kops-e2e-k8s-containerd

2020-11-09 03:36 UTC, hakman commented on upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
> +	actual.TargetGroups = make([]*TargetGroup, 0)
Is this really needed?

2020-11-09 03:36 UTC, hakman commented on upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
> +		actual.Listeners = make([]*NetworkLoadBalancerListener, 0)
Is this still needed?

2020-11-09 03:36 UTC, hakman commented on upup/pkg/fi/cloudup/awstasks/targetgroup.go
> +
Not quite by port. Name should be enough?

2020-11-09 23:28 UTC, rifelpet commented on upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
> +					actualListener.TargetGroupName = aws.StringValue(descResp.TargetGroups[0].TargetGroupName)
Not sure I understand, which field would we use with "compare by ID" ? We need a field that can be both provided by the model and something we can look up in `Find()`. It seems like our only options for that are TargetGroupName or tags.

2020-11-10 04:07 UTC, hakman commented on upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
> +					actualListener.TargetGroupName = aws.StringValue(descResp.TargetGroups[0].TargetGroupName)
I meant that at the time this runs there is also full info on target groups populated in `e.TargetGroups`, so you can just get the name from there without an extra call to `DescribeTargetGroups`.
Though this is an optimisation that can be done later.

2020-11-10 04:10 UTC, hakman commented on upup/pkg/fi/cloudup/awstasks/targetgroup.go
> +
Still curious, why compare both by Name and ARN? Names should be unique.

2020-11-10 04:40 UTC, rifelpet commented on upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
> +					actualListener.TargetGroupName = aws.StringValue(descResp.TargetGroups[0].TargetGroupName)
If we're removing a listener (and therefore target group), `e.TargetGroups` won't have the target group being removed so we wont be able to lookup its name from `e.TargetGroups`. We'd have to `DescribeTargetGroups` to find it.

Though maybe the value of `actualListener.TargetGroupName` doesn't actually matter for a listener being deleted? When we add target group deletion support we probably won't be using the `listener.TargetGroupName` to determine what to delete, instead just use `NLBTargetGroupName()` to determine all the possible TG names and look for any that exist in AWS that shouldn't and delete them. just thinking out loud here...

2020-11-10 04:46 UTC, hakman commented on upup/pkg/fi/cloudup/awstasks/network_load_balancer.go
> +					actualListener.TargetGroupName = aws.StringValue(descResp.TargetGroups[0].TargetGroupName)
If delete is done by ARN, probably no describing will be needed. I agree that the compare part should check which ones are removed and just delete them.

2020-11-10 15:12 UTC, hakman requested changes

2020-11-10 15:12 UTC, hakman commented on upup/pkg/fi/cloudup/awstasks/autoscalinggroup.go
```suggestion

	actual.TargetGroups = []*TargetGroup{}
```

2020-11-10 15:12 UTC, hakman commented on pkg/model/awsmodel/autoscalinggroup.go
>  	if !featureflag.Spotinst.Enabled() {
```suggestion
	t.TargetGroups = []*awstasks.TargetGroup{}
	if !featureflag.Spotinst.Enabled() {
```

2020-11-10 17:05 UTC, hakman commented
/lgtm

2020-11-10 17:47 UTC, rifelpet commented
/hold cancel

2020-11-10 18:36 UTC, merged