Add minimal cert-manager addon
kubernetes/kops pull request #10318
Opened 2020-11-26 08:25 UTC by olemarkus

There are several images involved here, so dropped the usual `Image` field until we have a better understanding how to handle this. Making at minimum the version configurable can be done well in time for 1.20 alpha anyway.

Adding this PR is a prereq for some other addons + the kops-controller issuer.

2020-11-26 08:52 UTC, hakman commented
I am a bit concerned about the 1.6 MB template that is being pulled into bindata.go also.

2020-11-26 09:27 UTC, olemarkus commented
Pretty huge CRDs. But can we do much about that?

2020-11-26 10:13 UTC, hakman commented
Not sure what can be done about it, but probably something should be done.

2020-11-26 17:32 UTC, olemarkus commented
https://github.com/jetstack/cert-manager/issues/3299

They are what they are. I can't think of a reason this would cause any harm.

2020-12-05 03:47 UTC, hakman requested changes
A few Q:
1. Why switch from the `cert-manager` namespace to `kube-system`?
2. Why limit running on master nodes?

2020-12-05 03:47 UTC, hakman commented on upup/pkg/fi/cloudup/bootstrapchannelbuilder.go
> +			version := "1.0.4"
```suggestion
			version := "1.1.0"
```

2020-12-05 06:25 UTC, olemarkus commented
>     Why switch from the cert-manager namespace to kube-system?

Kops could technically have its own namespace for addons that doesn't strictly need to be in kube-system. But we don't have anything like this. So when it comes to PSPs and such, we don't have much choice but to deploy it to kube-system.

> Why limit running on master nodes?

A lot of users run cert-manager on masters to leverage DNS ACME authentication. If/when we get IRSA more mature (and if this doesn't end up in a circular dependency) it could run on normal nodes using a dedicated IAM role.

2020-12-05 06:36 UTC, hakman commented
Thanks for the explanation.
/lgtm
/approve

2020-12-05 06:57 UTC, merged