WIP: Create toolbox command for rotating cluster CA
kubernetes/kops pull request #10516
Opened 2021-01-02 18:51 UTC by olemarkus

Pretty much following https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/ but in an order that makes sense for kOps

2021-02-04 08:31 UTC, olemarkus commented
/milestone v1.21

2021-04-09 05:34 UTC, olemarkus commented
/cc @johngmyers @justinsb

2021-04-10 04:34 UTC, johngmyers commented
My main concern with this is how the admin is supposed to recover if the command fails halfway through, for example with a power loss on the machine running kops.

I designed the similar WIP PR #9556 with smaller, atomic steps. In that PR, to fully distrust the previous keys one has to run the command three times, waiting enough time for tokens to be renewed between each run.

Like that PR, it might be easier to simplify by always keeping a "next CA" (and possibly "previous CA") in the trust list.

Another idea is to put a hash of the relevant CA set in userdata, so worker and/or control plane nodes will be detected as needing update by the rolling update code.

2021-04-10 05:11 UTC, olemarkus commented
We rotate the cluster twice in this case, once with a CA bundle where both certs are trusted, and once with only one the new CA after everything trust the new CA.

I have not managed to end up in a state where the cluster is broken. Only manage to lock myself out by explicitly exporting admin credentials signed with the new CA too early, before the api servers trust it.

2021-04-10 05:22 UTC, olemarkus commented
@johngmyers I see your PR is about SA signing token keys, which is much more messy as all api servers and all pods should rotate at exactly the same time. There is https://github.com/kubernetes/kubernetes/issues/20165 but it is pretty much unresolved

2021-04-10 05:48 UTC, johngmyers commented
@olemarkus my PR is about graceful rotation of SA signing token keys. It is not necessary for all API servers and pods to rotate at the same time.

Since kubernetes/kubernetes#20165 was filed the `--service-account-key-file` flag started taking multiple keys.

2021-04-10 07:47 UTC, olemarkus commented
Ah wasn't aware of that. Thanks. I need to have a look on how that one works then.

2021-04-12 05:57 UTC, johngmyers commented
@olemarkus Would you be willing to hold this for a while to give #11204 a chance to land first? I believe that puts down some infrastructure that would improve this PR.

2021-04-12 09:04 UTC, olemarkus commented
Yeah. I like the ability to decide when to move to the next key rather than always using the highest number. I think that may require an additional roll of the control plane though, as on the first roll, the kube-controller-manager would not use the new keys. Unless we tell it to always use the latest cert even if it is not primary.

2021-04-13 21:18 UTC, johngmyers requested changes

2021-04-13 21:18 UTC, johngmyers commented on cmd/kops/rotate_ca.go
> +
While the new certs/keys currently take effect without an `apply_cluster`, this is undesirable and there are plans to move more of this stuff to userdata and/or versioned files in the store. We should ensure that changing either the set of trusted CAs or the active CA causes the control plane nodes to be treated as "NeedsUpdate". We should also allow for a future need to do an `apply_cluster`.

2021-04-13 21:18 UTC, johngmyers commented on cmd/kops/rotate_ca.go
> +	//Update masters. This will issue new certs for k8s using the new CA.
```suggestion
	// Update control plane. This will issue new certs for k8s using the new CA.
```

2021-04-13 21:18 UTC, johngmyers commented on cmd/kops/rotate_ca.go
> +	klog.Info("rotating the control plane")
The new `certificate-authority-data` needs to be propagated to all the kubeconfig files that live outside the cluster before proceeding to change the signing CA. This is part of the reason I don't think this should be an "all in one go" type of command.

2021-04-13 21:32 UTC, johngmyers commented on cmd/kops/rotate_ca.go
> +	exportAdmin := clientConfig.Contexts[contextName].AuthInfo == contextName
This appears to be a bit too heuristic. It should check that the corresponding `AuthInfo` has nonempty `ClientCertificateData`

2021-04-13 21:34 UTC, johngmyers commented on cmd/kops/rotate_ca.go
> +		klog.Info("Secondary CA cert already in the pool. Not issuing a new CA")
What if the previous run died while removing trust from the old CA?

2021-04-13 22:50 UTC, johngmyers commented
Another reason I don't like an all-in-one command: We have a workload (rhymes with CrewBeeper) which frequently fails on a node rolling update. For this reason, we only do node rolling updates with a locally written controller. That controller implements local constraints, such as notifying the relevant workload's maintainers and delaying the update of their instance group until they can be on deck to fix the resulting failure of their workload. So we would not want the command that updates the keys to perform the rolling update.

2021-06-25 06:47 UTC, olemarkus commented
/close

Closing in favour of the great work done by John!

2021-06-25 06:47 UTC, closed without merging