Fix rendering issue created by #10414
kubernetes/kops pull request #10700
Opened 2021-01-31 09:20 UTC by avdhoot

This might break upgrade if cluster spec have `prometheusMetricsEnabled: true`. I have validated this by upgrading our cluster. This is caused by #10414

2021-01-31 09:29 UTC, olemarkus commented
/ok-to-test

2021-01-31 14:32 UTC, hakman requested changes
Thanks @avdhoot. Please also bump the manifest version here to `3.17.1-kops.3`:
https://github.com/kubernetes/kops/blob/40ae752e46182e60568eceff3d94dca39f79165a/upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go#L744

2021-02-01 04:48 UTC, hakman commented
Looks good. One more thing, if you don't mind, could you squash the 2 commits?

2021-02-01 08:42 UTC, avdhoot commented
@hakman Sorry took time to understand local `squash`. Thanks.

2021-02-04 08:17 UTC, olemarkus commented
/lgtm
/approve

2021-02-04 09:46 UTC, merged