Update node local dns cache and expose metrics
kubernetes/kops pull request #11057
Opened 2021-03-16 06:48 UTC by zetaab

2021-03-17 09:46 UTC, olemarkus requested changes
Looks good except for the headless service that I don't feel belongs as part of the addon.

2021-03-17 09:46 UTC, olemarkus commented on upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template
> +---
We don't ship these headless services typically used by prom operator as we don't ship prom operator either.

Also, `PodMonitor` avoids the need for these services.

2021-04-09 18:31 UTC, zetaab commented
@olemarkus I just updated the node local dns, maybe that is enough for now.

2021-04-09 18:41 UTC, olemarkus approved these changes
Thanks man

2021-04-09 19:25 UTC, merged