Give kOps CLI knowledge about ASG warm pools
kubernetes/kops pull request #11227
Opened 2021-04-13 11:05 UTC by olemarkus

* `kops get instances` mark warm pool nodes
* rolling update warm pool
   * Warm pool instances will terminate first
   * Warm pool instances will terminate without validation as they are not part of the cluster

Based on #11216 
/hold

2021-04-14 06:16 UTC, johngmyers requested changes
This capping of `maxSurge`

https://github.com/kubernetes/kops/blob/ab1b85818d3240c5b9b04bade5c0d3465ce7944d/pkg/instancegroups/instancegroups.go#L111-L113

needs to ignore warm instances in `update`, otherwise rolling update could end up detaching warm instances.

2021-04-14 06:16 UTC, johngmyers commented on pkg/instancegroups/instancegroups.go
> +		klog.Infof("%q is in the warm pool. Not sleeping", u.ID)
I don't think there's a need to log anything here.

2021-04-14 09:34 UTC, olemarkus commented
In `detachInstance`, I added a check for the state, so it should just return if an instance is in the warm pool. AWS will fail a detach instance call on a warm pool instance.

2021-04-14 15:58 UTC, olemarkus commented
@johngmyers you were right. there were dragons in my previous approach. Now I am a bit more brutish and just iterate over all the warmpool nodes and quickly terminate them immediately in the beginning.

2021-04-14 16:02 UTC, johngmyers commented
I like simple.

2021-04-14 17:51 UTC, olemarkus commented
/retest

2021-04-15 09:36 UTC, olemarkus commented
/hold cancel

2021-04-15 11:42 UTC, hakman approved these changes

2021-04-15 12:25 UTC, olemarkus commented
/test pull-kops-e2e-kubernetes-aws

2021-04-15 13:37 UTC, olemarkus commented
/test pull-kops-e2e-k8s-containerd

2021-04-15 14:04 UTC, hakman commented
/test all

2021-04-15 14:33 UTC, olemarkus commented
/retest

2021-04-15 15:10 UTC, olemarkus commented
/retest

2021-04-15 16:04 UTC, hakman commented
/retest

2021-04-15 16:46 UTC, merged

2021-04-15 16:48 UTC, johngmyers commented on pkg/instancegroups/instancegroups.go
> +		if instance.State == cloudinstances.WarmPool {
I don't think you need to delete them unless they're NeedsUpdate.