WIP [csi/aws] Bump templates to latest stable version
kubernetes/kops pull request #11304
Opened 2021-04-24 05:03 UTC by dntosas

Signed-off-by: dntosas <ntosas@gmail.com>

2021-04-24 05:21 UTC, olemarkus commented
/ok-to-test

2021-04-24 08:12 UTC, dntosas commented
qq: where IAM resources that described in [here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/example-iam-policy.json) are handled?

2021-04-24 08:15 UTC, olemarkus commented
they are handled in `pkg/model/iam/iam_builder.go`.

It would be nice to collect all the privs needed for CSI to one function though, to make this more maintainable. That would also allow us to use IRSA for this addon further down the road.

2021-04-24 08:54 UTC, dntosas commented
@olemarkus are not IAM permissions for attaching etc volumes should be present on regular nodes role also? without them how will the pods of node daemonSet can be allowed to do such operations?

2021-04-24 08:58 UTC, olemarkus commented
As I understand it, it is the ebs-csi-controller that does the AWS calls. The purpose of the DaemonSet is to extend kubelet with the driver specific functionality.

2021-04-24 09:03 UTC, dntosas commented
> As I understand it, it is the ebs-csi-controller that does the AWS calls. The purpose of the DaemonSet is to extend kubelet with the driver specific functionality.

y makes sense ^^

2021-04-24 14:38 UTC, johngmyers commented
I don't see the code for calculating the default value of `Version`

2021-04-24 18:09 UTC, dntosas commented
@johngmyers i thought something like [this](https://github.com/kubernetes/kops/blob/e8c8b92b95b49aba161f13a67f080b28c39abe97/upup/models/cloudup/resources/addons/aws-ebs-csi-driver.addons.k8s.io/k8s-1.17.yaml.template#L249) should be enough ^^ if there is a more proper way or place to implement this logic, can you give a hint on where to look?

2021-04-24 21:25 UTC, johngmyers commented
@dntosas Okay, that does work; I had missed that. Unfortunately it is error prone to have the version in so many places. If one gets missed on an update that is unlikely to be caught in code review.

The other way is to define a template function, like https://github.com/kubernetes/kops/blob/dbd23473efe25c7eca1576f462b60233cd715d4d/upup/pkg/fi/cloudup/template_functions.go#L588-L608

2021-04-25 08:18 UTC, dntosas commented
@olemarkus @johngmyers thanks for your help :)

pushed changes, i think we are better now ^^

2021-04-25 08:46 UTC, olemarkus requested changes

2021-04-25 08:46 UTC, olemarkus commented on pkg/apis/kops/componentconfig.go
> +	// Version of the CSI controller container
Nit: go comments should have proper punctuation.

2021-04-25 08:46 UTC, olemarkus commented on pkg/model/components/awsebscsidriver.go
> +	if c.Enabled == nil {
nit: this check is typically noops as we tend to use `if fi.BoolValue()` which defaults to false.
And you _have_ to use `{{ if WithDefaultBool <defaultVaule> }}` in templates as templates will only check if the pointer is nil or not.

2021-04-25 08:47 UTC, olemarkus commented
Just a few nits, otherwise looks good to go to me.

2021-04-26 06:16 UTC, dntosas commented
/retest

2021-04-26 09:30 UTC, olemarkus approved these changes

2021-04-26 09:37 UTC, merged