[addons/networking.cilium.io] enable prometheus scraping
kubernetes/kops pull request #11514
Opened 2021-05-18 12:53 UTC by ulfox

When EnablePromethesMetrics is enabled the
required metrics endpoints are exposed but
no annotations is included in the agents.

This commit includes the prometheus.io/scrape
and prometheus.io/port annotations that
prometheus scrappers can use for auto-discovery

Co-authored-by: tchatzig <t.chatzigeorgiou@thebeat.co>

2021-05-18 13:37 UTC, ulfox commented
signed

2021-05-18 15:40 UTC, johngmyers requested changes

2021-05-18 15:40 UTC, johngmyers commented on upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
> +        # Annotation required for prometheus auto-discovery scrapping
```suggestion
        # Annotation required for prometheus auto-discovery scraping
```

2021-05-18 15:40 UTC, johngmyers commented on upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template
> +        # Annotation required for prometheus auto-discovery scrapping
```suggestion
        # Annotation required for prometheus auto-discovery scraping
```

2021-05-18 15:40 UTC, johngmyers commented on upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.16-v1.10.yaml.template
> +        # Annotation required for prometheus auto-discovery scrapping
```suggestion
        # Annotation required for prometheus auto-discovery scraping
```

2021-05-18 16:19 UTC, ulfox commented
/retest

2021-05-19 04:33 UTC, johngmyers commented on upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.8.yaml.template
> +        {{ if .EnablePrometheusMetrics }}
This is outside of any `{{ with .Networking.Cilium }}` block.

2021-05-19 15:57 UTC, johngmyers approved these changes
Thanks!

2021-05-19 17:12 UTC, merged