[cilium] Add support for encryption via WireGuard
kubernetes/kops pull request #11786
Opened 2021-06-16 13:41 UTC by dntosas

In this commit, we enable users to choose WireGuard as their prefered
encryption type, leveraging this new feature from Cilium.

Ref: https://cilium.io/blog/2021/05/20/cilium-110#wireguard

Signed-off-by: dntosas <ntosas@gmail.com>

2021-06-16 16:24 UTC, johngmyers commented on pkg/apis/kops/validation/validation.go
> +		allErrs = append(allErrs, IsValidValue(fldPath.Child("encryptionType"), &v.EncryptionType, []string{"ipsec", "wireguard"})...)
Should do a Cilium version check for wireguard

2021-06-16 16:25 UTC, johngmyers commented
/ok-to-test

2021-06-16 16:25 UTC, johngmyers commented
/cc @olemarkus

2021-06-17 06:08 UTC, olemarkus commented
/retest

2021-06-18 08:24 UTC, olemarkus commented
Ubuntu LTS requires the wireguard package being installed, I believe.
If you set `encryptionConfig` I think kOps will also require the `ciliumpassword` secret. Is this one needed for wireguard?

It would also be nice to add some docs on how to enable wireguard.

2021-07-04 02:24 UTC, johngmyers commented
/assign @olemarkus

2021-07-04 05:40 UTC, olemarkus requested changes
See comments above

2021-07-09 09:57 UTC, dntosas commented
FYI, will be able continue it early next week team ^^

2021-08-05 14:31 UTC, choutone commented
Hi @dntosas,
I'm really interested to use Cilium with Wireguard via Kops. Any update on this PR? :cry:

2021-08-17 11:02 UTC, olemarkus commented
/close

Closed in favour of #12158

2021-08-17 11:02 UTC, closed without merging