Seed the random number generator on AWS
kubernetes/kops pull request #11789
Opened 2021-06-16 19:45 UTC by johngmyers

2021-06-16 20:30 UTC, johngmyers commented
/retest

2021-06-17 06:11 UTC, johngmyers commented
/retest

2021-06-18 10:38 UTC, hakman requested changes

2021-06-18 10:38 UTC, hakman commented on upup/pkg/fi/nodeup/command.go
> +// getRegionAndSeedRNG queries the cloud provider for the region and adds entropy to the random number generator.
```suggestion
// getRegion queries the cloud provider for the region.
```

2021-06-18 15:13 UTC, johngmyers commented on pkg/model/tests/data/bootstrapscript_0.txt
> +CloudProvider: ""
Possibly. It's outside the scope of this PR, though.

2021-06-18 15:35 UTC, hakman approved these changes

2021-06-18 15:48 UTC, merged

2021-06-19 02:55 UTC, johngmyers commented on pkg/model/tests/data/bootstrapscript_0.txt
> +CloudProvider: ""
The cloud provider is set in code which is outside the scope of these tests.