Add podPidsLimit / --pod-max-pids support
kubernetes/kops pull request #11898
Opened 2021-07-01 00:09 UTC by uthark

Decided to use the same name as in [Kubelet config](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/types.go#L260-L261)

This will allow user to configure the PID limit per pod.

2021-07-01 00:23 UTC, grosser approved these changes

2021-07-01 00:27 UTC, uthark commented
/assign @rdrgmnzs

2021-07-01 02:12 UTC, hakman commented
/ok-to-test

2021-07-01 02:30 UTC, hakman requested changes

2021-07-01 02:30 UTC, hakman commented on pkg/apis/kops/componentconfig.go
> +	PodPidsLimit *int64 `json:"podPidsLimit" flag:"pod-max-pids"`
```suggestion
	PodPidsLimit *int64 `json:"podPidsLimit,omitempty" flag:"pod-max-pids"`
```

2021-07-01 02:30 UTC, hakman commented on pkg/apis/kops/v1alpha2/componentconfig.go
> +	PodPidsLimit *int64 `json:"podPidsLimit" flag:"pod-max-pids"`
```suggestion
	PodPidsLimit *int64 `json:"podPidsLimit,omitempty" flag:"pod-max-pids"`
```

2021-07-07 03:15 UTC, hakman approved these changes
Thanks @uthark!

2021-07-07 03:22 UTC, merged