Make AWS CCM NodeIPFamilies configurable
kubernetes/kops pull request #12305
Opened 2021-09-11 08:06 UTC by hakman

Default to IPv6 + IPv4 but allow setting IPv6 or IPv4 only.

/cc @olemarkus @johngmyers

2021-09-11 08:54 UTC, olemarkus requested changes

2021-09-11 08:54 UTC, olemarkus commented on pkg/apis/kops/componentconfig.go
> +	NodeIPFamilies []string `json:"nodeIPFamilies,omitempty"`
This flag should probably be in `kops.CloudConfiguration` together with the other flags that affects the `cloud.config` file.

2021-09-11 10:10 UTC, hakman commented
/test pull-kops-e2e-ipv6-conformance

2021-09-11 10:11 UTC, hakman commented on nodeup/pkg/model/cloudconfig.go
> +				lines = append(lines, "NodeIPFamilies = ipv6, ipv4")
OK, let's see how this goes.

2021-09-12 12:44 UTC, olemarkus approved these changes

2021-09-12 13:26 UTC, merged