Do not allow docker on k8s 1.24+
kubernetes/kops pull request #12927
Opened 2021-12-11 07:06 UTC by olemarkus

2021-12-11 07:17 UTC, hakman commented
Should we wait for https://github.com/kubernetes/kubernetes/pull/106907 to merge first?

2021-12-11 07:33 UTC, olemarkus commented
We can, but I don't think it really changes anything more on our end. Not that I can see at least.

2021-12-11 07:35 UTC, hakman commented
Mean in case there is a decision to postpone it.

2021-12-11 07:40 UTC, olemarkus commented
Think that is unlikely, but I have no problem with waiting a bit

2021-12-18 12:14 UTC, hakman requested changes
Considering https://github.com/kubernetes/kubernetes/pull/97252 was merged, I think it's safe to merge this too.

2021-12-18 12:14 UTC, hakman commented on pkg/apis/kops/validation/validation.go
> +		allErrs = append(allErrs, field.Forbidden(fldPath, "docker is not supported by Kubernetes 1.24 and above"))
```suggestion
		allErrs = append(allErrs, field.Forbidden(fldPath, "Docker CRI support was removed in Kubernetes 1.24: https://kubernetes.io/blog/2020/12/02/dockershim-faq"))
```

2021-12-18 12:14 UTC, hakman commented
/lgtm

2021-12-19 11:45 UTC, hakman approved these changes

2021-12-19 12:17 UTC, merged