WIP Add a CLI flag for creating one karpenter-managed IG for worker nodes instead of ASG-managed ones
kubernetes/kops pull request #12975
Opened 2021-12-15 09:12 UTC by olemarkus

This PR adds a flag `--instance-manager` if the karpenter feature flag is enabled. This flag will create one single karpenter IG instead of per-AZ ASG IGs.

This will allow us to easily test karpenter-only clusters, and give users an easy way of testing karpenter.

At the moment, this PR also includes various other fixes as well required for Karpenter to work.

2021-12-21 22:19 UTC, johngmyers requested changes

2021-12-21 22:19 UTC, johngmyers commented on cmd/kops/create_cluster.go
> +		cmd.Flags().StringVar(&options.InstanceManager, "instance-manager", options.InstanceManager, "Instance manager to use (cloudgroups or kapenter. Default: cloudgroups)")
```suggestion
		cmd.Flags().StringVar(&options.InstanceManager, "instance-manager", options.InstanceManager, "Instance manager to use (cloudgroups or karpenter. Default: cloudgroups)")
		cmd.RegisterFlagCompletionFunc("instance-manager", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return []string{"cloudgroups", "karpenter"}, cobra.ShellCompDirectiveNoFileComp
	})
```

2021-12-21 22:19 UTC, johngmyers commented on upup/pkg/fi/cloudup/new_cluster.go
> +	// InstanceManager specifies which manager to use for managing instances
```suggestion
	// InstanceManager specifies which manager to use for managing instances.
```

2021-12-21 22:30 UTC, johngmyers commented on upup/pkg/fi/cloudup/new_cluster.go
> +	} else {
Shouldn't we validate the `InstanceManager` is `cloudgroups` here?

2021-12-23 22:49 UTC, johngmyers commented on upup/pkg/fi/cloudup/new_cluster.go
> +	g.ObjectMeta.Name = "karpenter-nodes"
Shoudn't we call this just `nodes`?

2021-12-24 08:20 UTC, olemarkus commented on upup/pkg/fi/cloudup/new_cluster.go
> +	g.ObjectMeta.Name = "karpenter-nodes"
yeah we should

2021-12-24 08:41 UTC, johngmyers approved these changes

2021-12-24 09:40 UTC, merged