Included githubactions in dependabot config
kubernetes/kops pull request #13423
Opened 2022-03-27 18:10 UTC by naveensrinivasan

**What this PR does / why we need it**:

- Included githubactions in the dependabot config

This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

2022-03-27 18:12 UTC, naveensrinivasan commented
A similar one was merged in another k8s repo https://github.com/kubernetes/minikube/pull/13770

2022-03-27 18:13 UTC, naveensrinivasan commented
@olemarkus  👀  please. Thanks

2022-03-27 18:13 UTC, naveensrinivasan commented
/assign @olemarkus

2022-03-28 01:14 UTC, hakman commented
@naveensrinivasan I appreciate the contribution, but at the moment using dependabot is not usable in the kOps repo due to heavy bazel usage. Also, at least k8s deps should be excluded.
/hold

2022-03-28 01:19 UTC, hakman commented
Got this wrong, it's only about github actions, not gomod (yet).
/hold cancel

2022-03-28 01:53 UTC, hakman requested changes

2022-03-28 01:53 UTC, hakman commented on .github/dependabot.yml
> +      interval: "weekly"
```suggestion
    interval: "weekly"
    day: "sunday"
  labels:
  - "ok-to-test"
```

2022-03-28 01:58 UTC, naveensrinivasan commented
Thanks for the suggestion.

2022-03-28 02:09 UTC, hakman commented
/lgtm

2022-03-28 02:10 UTC, hakman commented
/ok-to-test

2022-03-28 05:07 UTC, olemarkus approved these changes

2022-03-28 05:32 UTC, hakman commented
/retest

2022-03-28 06:16 UTC, hakman commented
/retest

2022-03-28 11:39 UTC, hakman commented
/retest

2022-03-28 13:29 UTC, merged