Deprecate cluster name as positional argument
kubernetes/kops pull request #14076
Opened 2022-07-31 07:14 UTC by olemarkus

Mixing sub commands and positional args (e.g `kops get cluster` vs `kops get foo.k8s.local`) is confusing. It also complicates the arg/flag logic. This PR deprecates the use of cluster name as positional argument and nudges people over to always using `--name`.

2022-07-31 09:22 UTC, hakman requested changes

2022-07-31 09:22 UTC, hakman commented on cmd/kops/root.go
> +	}
```suggestion
	if len(args) > 0 {
		fmt.Printf("\n")
		fmt.Printf("\nClusterName as positional argument is deprecated and will be removed\n")
		fmt.Printf("Use `KOPS_FEATURE_FLAGS=PositionalClusterArg` to revert to the old behavior.")
		fmt.Printf("\n")
	}
	if !featureflag.PositionalClusterArg.Enabled() {
		return nil
	}
```

2022-07-31 09:22 UTC, hakman commented on docs/releases/1.25-NOTES.md
> +This change is behind a feature flag. One can revert to the old behavior by setting `KOPS_FEATURE_FLAGS=EnablePositionalClusterArg`.
```suggestion
This change is behind a feature flag. For now, one can revert to the old behavior by setting `KOPS_FEATURE_FLAGS=PositionalClusterArg`.
```

2022-07-31 16:12 UTC, hakman approved these changes

2022-07-31 16:14 UTC, merged

2022-08-03 14:08 UTC, justinsb commented
This does break user workflows, and does deviate from what kubectl does.

I do agree that `kops get clustername` is an abberation ... we could replace that with `kops get all <clustername>` or similar, as that might be clearer all round.

We could also make this a warning and remove the functionality in a future release; right now we immediately break scripts etc I think.

2022-08-03 15:05 UTC, olemarkus commented
I think we already deviate from kubectl in many ways. My original idea was to only print a deprecation warning, but I don't have too strong opinion so I went with @hakman's suggestion. We could also drop the `--name` flag, I suppose, but I want to get rid from the ambigous parsing that comes from `ProcessArgs`.