Calico: Work around host port/conntrack problem
kubernetes/kops pull request #14205
Opened 2022-08-30 18:54 UTC by seh

In Calico's released versions, per projectcalico/calico#6522, when using the eBPF data plane, containers using host ports cannot respond to connection attempts correctly. These container receive the packets from the client forwarded after DNAT, but when they reply, there is no conntrack entry for the would-be connection, so _netfilter_ drops the reply packets, preventing the connection from completing. The client never receives the reply packets. The conntrack entry is missing because Calico mistakenly attempts to optimize it away.

Work around the problem by disabling [the Calico Felix program's 
"BPFHostConntrackBypass" feature](https://projectcalico.docs.tigera.io/reference/felix/configuration#ebpf-dataplane-configuration). This is a temporary measure until the Calico maintainers can improve this feature to better handle host port traffic, preserving these conntrack entries as intended.

See [the related discussion in the "networking" channel](https://calicousers.slack.com/archives/CPEPF833L/p1661868642674109) of the "Calico Users" Slack workspace, in which @tomastigera suggested this fix.

2022-08-30 19:42 UTC, seh commented
See projectcalico/calico#6641 for being able to employ this same workaround in a _FelixConfiguration_ Kubernetes object.

2022-08-31 04:57 UTC, hakman requested changes

2022-08-31 04:57 UTC, hakman commented on upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.16.yaml.template
> +            {{- end }}
No reason to do it for older Calico.

2022-08-31 04:57 UTC, hakman commented on upup/models/cloudup/resources/addons/networking.projectcalico.org/k8s-1.22.yaml.template
> +            # through DNAT reversal properly.
```suggestion
            # Temporary workaround for https://github.com/projectcalico/calico/issues/6522,
            # allowing reply packets from containers using host ports to flow through DNAT reversal properly.
```

2022-08-31 06:36 UTC, hakman approved these changes

2022-08-31 07:09 UTC, merged