Use generics to refactor fi.Bool/Int/Float/String*()
kubernetes/kops pull request #14592
Opened 2022-11-18 15:18 UTC by hakman

2022-11-18 16:56 UTC, johngmyers commented
I'm not sure about `NumberValue()`. Go can't have a `Value()`?

One would think something like `PtrTo()` would make its way into the standard libraries.

2022-11-18 17:00 UTC, johngmyers requested changes

2022-11-18 17:00 UTC, johngmyers commented on upup/pkg/fi/values.go
> +// PtrTo returns a pointer to any value
```suggestion
// PtrTo returns a pointer to a copy of any value
```

2022-11-18 17:02 UTC, hakman commented
> I'm not sure about `NumberValue()`. Go can't have a `Value()`?

No idea, was just something fun to do. Seemed more "number" like, as we still have `StringValue()` and `BoolValue()`.

> One would think something like `PtrTo()` would make its way into the standard libraries.

That would be nice.

2022-11-19 17:16 UTC, johngmyers approved these changes

2022-11-19 18:08 UTC, merged