fix: use viper to get configuration strings
kubernetes/kops pull request #14642
Opened 2022-11-23 17:55 UTC by remyleone

I would like to use a configuration file stored in `~/.kops.yaml` to store my credentials and many configuration preferences that will remain constant across several cluster creations. Therefore, I think it would be useful to use the helper `viper.GetString` to get information from the configuration file and in case they are not defined there, it will be go to the environment variables.

I guess we would need to do that across all Kops. At the moment many configuration options are not working for me when they are defined in the configuration file and not with environment variables without the use of `viper.GetString()`.

2022-11-23 18:51 UTC, hakman commented
Running `make gomod` should fix the missing deps.

2022-11-23 20:14 UTC, remyleone commented
@hakman I'm not sure about how to mock credentials in the context of this test

2022-11-23 20:50 UTC, remyleone commented
I've tried to do a search and replace across the whole code base and it seems to work except for this test

2022-11-23 22:51 UTC, johngmyers commented
Viper isn't seeing the change to the environment variable that is done in the test setup. The test setup probably has to be changed to push the value into viper (and clear it aterwards).

2022-12-01 07:07 UTC, hakman commented on util/pkg/vfs/tests/s3fs_test.go
> +	viper.Set("KOPS_STATE_S3_ACL", "bucket-owner-full-control")
This is not really required. The problem is mainly that `viper.BindEnv("ENV_VAR")` has to be called before using `viper.GetString("ENV_VAR")`.

2022-12-01 07:10 UTC, hakman requested changes

2022-12-01 07:10 UTC, hakman commented on util/pkg/vfs/s3context.go
> +	endpoint := viper.GetString("S3_ENDPOINT")
Calling `viper.BindEnv()` should make env reading possible. A little annoying, but not sure how to go about it differently at the moment.
```suggestion
	_ = viper.BindEnv("S3_ENDPOINT")
	endpoint := viper.GetString("S3_ENDPOINT")
```

2022-12-12 17:13 UTC, remyleone commented
@hakman could you review again? :)

2022-12-16 08:29 UTC, hakman requested changes

2022-12-16 08:29 UTC, hakman commented on pkg/featureflag/featureflag.go
> +	ParseFlags(viper.GetString(Name))
I think `viper.BindEnv()` would be required here also.
```suggestion
	_ = viper.BindEnv(Name)
	ParseFlags(viper.GetString(Name))
```

2022-12-16 08:31 UTC, hakman commented
@johngmyers Could you take a look too?

2022-12-18 18:50 UTC, johngmyers commented
I think we need a coherent strategy for using viper, probably that of https://github.com/carolynvs/stingoftheviper. I would prefer the viper keys be lowercase hyphen-separated, using the flag names, not all-caps underscore-separated.

2023-03-28 04:50 UTC, hakman commented
@remyleone Would you mind rebasing to address https://github.com/kubernetes/kops/pull/14642#issuecomment-1462082897?

2023-04-27 14:35 UTC, hakman commented
@remyleone Could you remove the go.mod & go.sum changes and squash the commits?

2023-07-27 03:10 UTC, hakman commented
/cc @johngmyers @justinsb 
/kind office-hours

2023-07-27 13:37 UTC, johngmyers commented
I think my comments of Dec 18, 2022 are still relevant. We definitely shouldn't be defining new all-caps viper keys.

2023-07-27 14:39 UTC, hakman commented
> I think my comments of Dec 18, 2022 are still relevant. We definitely shouldn't be defining new all-caps viper keys.

To answer your comment from Dec 18, https://github.com/carolynvs/stingoftheviper may work in the example, but could not get it to work in practice.

Also, I only want to redo the way we do things for the existing env vars for cloud provider, cluster, state store and some other things used for development.

2024-06-16 06:51 UTC, closed without merging