vfs: don't cache bucketDetails in S3Path
kubernetes/kops pull request #14945
Opened 2023-01-03 20:23 UTC by justinsb

We cache it in the S3Context anyway, and this potentially avoids some
race conditions (albeit likely harmless race conditions).

2023-01-03 20:46 UTC, johngmyers commented
/retest

2023-01-03 21:47 UTC, johngmyers requested changes

2023-01-03 21:47 UTC, johngmyers commented on util/pkg/vfs/s3fs.go
> +func (p *S3Path) ensureBucketDetails(ctx context.Context) (*S3BucketDetails, error) {
```suggestion
func (p *S3Path) getBucketDetails(ctx context.Context) (*S3BucketDetails, error) {
```

2023-01-04 13:27 UTC, justinsb commented on util/pkg/vfs/s3fs.go
> +func (p *S3Path) ensureBucketDetails(ctx context.Context) (*S3BucketDetails, error) {
Good call - done!

2023-01-04 16:26 UTC, merged