make openstack kops-controller boostrap auth better
kubernetes/kops pull request #15024
Opened 2023-01-19 08:07 UTC by zetaab

2023-01-19 08:11 UTC, zetaab commented on nodeup/pkg/bootstrap/install.go
> +	manifest.Set("Unit", "ConditionPathExists", "!/srv/kubernetes/kubelet-server.crt")
if I understood correctly we cannot use this in AWS? Is there easy way how we could pass cloud information to this package @olemarkus

2023-01-23 06:28 UTC, zetaab commented
@johngmyers @hakman could you check this? Currently in master (and in 1.26) we do not have bullet proof version

2023-01-23 06:33 UTC, hakman requested changes
/lgtm

2023-01-23 06:33 UTC, hakman commented on upup/pkg/fi/cloudup/openstack/verifier.go
> +}
This should be inlined in `newClientSet()`.

2023-01-23 07:20 UTC, merged