exit gracefully if server already exists in k8s
kubernetes/kops pull request #15138
Opened 2023-02-12 14:15 UTC by zetaab

Original issue for this is https://github.com/kubernetes/kops/issues/15057 but it was reverted due to other issues in https://github.com/kubernetes/kops/pull/15129

some discussion available in https://github.com/kubernetes/kops/pull/15114#pullrequestreview-1287780870

I have verified that this solution works in OpenStack. When existing instance tries to join again to cluster:

kops-controller log:
```
kops-controller-t4b8j kops-controller I0212 14:11:02.063861       1 server.go:148] 10.2.96.248:59480: instance already exists in kubernetes cluster
```

node log
```
Feb 12 14:11:03 nodes-helpa-fctnib nodeup[669]: I0212 14:11:03.187949     669 client.go:156] bootstrap request responded with code 204
Feb 12 14:11:03 nodes-helpa-fctnib systemd[1]: kops-configuration.service: Succeeded.
Feb 12 14:11:03 nodes-helpa-fctnib systemd[1]: Finished Run kOps bootstrap (nodeup).
```

So it works like planned. The only possible problem in this solution is that if someone do have older than 455 days https://github.com/kubernetes/kops/blob/master/cmd/kops-controller/pkg/server/server.go#L188 kubelet, the cert will expiry and it cannot renew the cert because it will be still part of the Kubernetes cluster. Currently the workaround for that is delete the node manually `kubectl delete node...` and restart it in cloudprovider. After that the node can request the new certificate. I do not see any other easy way to allow that without giving access to normal pods to request new certificates. 

cc @justinsb @hakman

2023-02-12 14:28 UTC, hakman commented
/hold for 1-2 days for more feedback

2023-02-12 14:32 UTC, hakman requested changes

2023-02-12 14:32 UTC, hakman commented on pkg/kopscontrollerclient/client.go
> +		klog.Infof("bootstrap request responded with code %d", response.StatusCode)
```suggestion
		klog.Infof("kops-controller returned status code %d", response.StatusCode)
```

2023-02-12 14:32 UTC, hakman commented on pkg/bootstrap/authenticate.go
> +var ErrAlreadyExists = errors.New("instance already exists in kubernetes cluster")
```suggestion
var ErrAlreadyExists = errors.New("node already exists")
```

2023-02-15 14:04 UTC, justinsb commented on cmd/kops-controller/pkg/server/server.go
> +			w.WriteHeader(http.StatusNoContent)
Nit-picking, but we could also do http.StatusConflict - that's what I've seen from GCP APIs at least.

2023-02-15 14:05 UTC, justinsb commented
One nit pick on the http status code, but I like this approach - a specific response, and exit with 0 :+1:

2023-02-15 14:11 UTC, justinsb commented
On the expiry side, I think we should figure out what behaviour we want here when the node already exists.  IIUC this is mostly a security defense-in-depth, so as we beef up auth here (e.g. the [node callback](https://github.com/kubernetes/kops/pull/15125) ) then we might not need it at all.  Whatever we decide, I'd like for us to try to converge the various clouds so they have similar behvaior here.

Anyway, I don't think my nit on the status code is blocking ....

/lgtm

2023-02-15 14:46 UTC, hakman commented
> On the expiry side, I think we should figure out what behaviour we want here when the node already exists. IIUC this is mostly a security defense-in-depth, so as we beef up auth here (e.g. the [node callback](https://github.com/kubernetes/kops/pull/15125) ) then we might not need it at all. Whatever we decide, I'd like for us to try to converge the various clouds so they have similar behvaior here.

It is also nice to know that the node config is sent only once and we don't update it dynamically on reboot, if something changes in the IG config.

2023-02-20 11:02 UTC, hakman approved these changes

2023-02-20 11:49 UTC, merged