If specified, posts event data to URL upon instance interruption action.
kubernetes/kops pull request #15151
Opened 2023-02-13 15:51 UTC by voriol

If specified, posts event data to URL upon instance interruption action

https://github.com/kubernetes/kops/pull/14562

2023-02-14 07:39 UTC, olemarkus commented
/ok-to-test

Except for tests being outdated, it looks good. Can you please add release notes too?

2023-02-14 09:13 UTC, olemarkus commented
This can be cherry picked into 1.26 if we get this in soon.

2023-02-16 10:12 UTC, voriol commented
Hi @olemarkus, is all OK or i need to do something with the tests?? Thanks!

2023-02-16 11:05 UTC, hakman commented
Try running `hack/update-expected.sh`.

2023-02-16 18:04 UTC, hakman commented
/retest

2023-03-14 07:02 UTC, voriol commented
hello! Do you think it is interesting to end this pull request?

sorry, I am not able to understand what is failing, I need help to pull this off.

if you prefer I can close it as "unresolved".

thank you

2023-08-04 14:36 UTC, hakman requested changes

2023-08-04 14:36 UTC, hakman commented on upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template
> +              value: {{ .WebhookURL }}
```suggestion
            {{ if .WebhookURL }}
            - name: WEBHOOK_URL
              value: {{ .WebhookURL }}
            {{ end }}
```

2023-08-04 14:36 UTC, hakman commented on upup/models/cloudup/resources/addons/node-termination-handler.aws/k8s-1.11.yaml.template
> +              value: {{ .WebhookURL }}
```suggestion
            {{ if .WebhookURL }}
            - name: WEBHOOK_URL
              value: {{ .WebhookURL }}
            {{ end }}
```

2023-08-04 14:37 UTC, hakman commented
@voriol Sorry for the late review. Please see my suggestions in case you still want to merge this. Thanks!

2023-08-04 14:37 UTC, hakman commented
/remove-lifecycle rotten

2023-08-04 16:11 UTC, voriol commented
hi @hakman, thanks for your review, better late than never :heart: 

I'll take a look between now and next week

thanks again

2023-08-04 16:31 UTC, hakman commented
> hi @hakman, thanks for your review, better late than never ❤️
> 
> I'll take a look between now and next week
> 
> thanks again

Once you have some time, please run `hack/update-expected` and squash the commits and move the release note to 1.28.

2023-08-07 12:29 UTC, voriol commented
/approve cancel

2023-08-07 12:32 UTC, closed without merging