scaleway: dns support
kubernetes/kops pull request #15393
Opened 2023-05-10 13:19 UTC by Mia-Cross

This PR adds support for DNS in Scaleway clusters.

[OUTDATED]
As it is, the integration tests can only be run by me because of the 2 constant variables : 
- `validDNSZone` is a domain name on which I have the rights.
- `validScalewayProfileName` is used to load my credentials from a local file in order to interact with it.
I'm not really sure what I should put instead for anybody to be able to run the tests, so I'll take any suggestion.

2023-05-10 13:30 UTC, hakman commented
@Mia-Cross Unrelated to this PR, is there a plan to add support for `--dns=none`?

2023-05-10 13:34 UTC, Mia-Cross commented
@hakman Yes, I plan to do it soon !

2023-05-11 08:12 UTC, hakman commented
/cc @justinsb

2023-05-11 10:30 UTC, hakman commented
kOps integration tests are based on mock clients. Not all clouds implement those though.
See: https://github.com/kubernetes/kops/tree/master/cloudmock

Not quite sure how to proceed here without the mock client, except by removing the integration tests and adding them back in a later PR, when a mock client is available.

2023-05-17 12:44 UTC, Mia-Cross commented
/test pull-kops-e2e-k8s-gce-cilium

2023-05-19 15:21 UTC, justinsb commented on dnsprovider/pkg/dnsprovider/providers/scaleway/dns.go
> +					if recordNameWithZone == dns.EnsureDotSuffix(rrset.Name()) {
Do we want to check the type here also?

2023-05-19 15:22 UTC, justinsb commented on dnsprovider/pkg/dnsprovider/providers/scaleway/dns.go
> +				if recordNameWithZone == dns.EnsureDotSuffix(rrset.Name()) && record.Data == rrset.Rrdatas()[0] {
And do we want to check the type here also?

2023-05-19 15:23 UTC, justinsb commented on dnsprovider/pkg/dnsprovider/providers/scaleway/dns_test.go
> +		name:      "dns.test.fr",
Nit: We normally use example.com - it's reserved for tests/examples: https://en.wikipedia.org/wiki/Example.com

(Maybe test.fr is also though?)

Not a blocker!

2023-05-19 15:28 UTC, justinsb commented
This looks great - thank you @Mia-Cross 

One question about whether the key of DNS records should be the record name + record type, that is how the DNS works on most other clouds.  Other than that, just a few non-blocking nits.

2023-05-26 15:57 UTC, Mia-Cross commented
@justinsb I've applied the recommended changes. About the record type, I had only tested with type A records so I didn't think of this but it seems like a good idea indeed to include the type of record in the key. Is there anywhere else where I should make the change ?

2023-06-17 10:28 UTC, justinsb commented
Thanks @Mia-Cross  - this looks great!  I'm not aware of any other places that the record type is not included (at least any place where it is significant, as we do mostly use A and AAAA records!)

/approve
/lgtm

2023-06-17 12:18 UTC, hakman commented on vendor/github.com/scaleway/scaleway-sdk-go/api/domain/v2beta1/domain_sdk.go
> +// API: domains and DNS API documetation.
```suggestion
// API: domains and DNS API.
```

2023-06-17 12:18 UTC, hakman commented on vendor/github.com/scaleway/scaleway-sdk-go/api/domain/v2beta1/domain_sdk.go
> +// RegistrarAPI: domains registrar API.
```suggestion
// RegistrarAPI: domains and DNS - Registrar API.
```

2023-06-17 12:25 UTC, hakman commented
/lgtm cancel

2023-06-17 12:28 UTC, hakman requested changes
I think `make gomod` is needed.

2023-06-19 11:30 UTC, hakman commented
/lgtm

2023-06-19 11:30 UTC, merged