docs: revise the bastion ssh guideline to mitigate permission denied errors
kubernetes/kops pull request #15657
Opened 2023-07-17 15:03 UTC by techieforfun

- Updated the username variable to avoid encountering the "Permission denied (publickey)" error in different AMIs
- Removed redundant description.

2023-07-17 15:16 UTC, hakman commented
/cc @johngmyers

2023-07-17 16:45 UTC, justinsb commented
Thanks @techieforfun - these changes lgtm!

/ok-to-test
/lgtm
/approve

/hold for a few hours to give others a chance to review, but lgtm

2023-07-18 03:52 UTC, johngmyers requested changes
The "Access when using gossip" section also applies to none-dns. This isn't a blocking comment.

2023-07-18 03:52 UTC, johngmyers commented on docs/bastion.md
> +ssh -A <username>@<bastion-ELB-address>
```suggestion
# Now you can SSH into the bastion. Substitute the administrative username of the instance's OS for <username> (`ubuntu` for  Ubuntu,  `admin` for Debian, etc.) and the bastion domain for <bastion-domain>. If the bastion doesn't have a public CNAME alias, use the domain of the assigned load balancer as the bastion domain.
ssh -A <username>@<bastion-domain>
```

2023-07-18 03:52 UTC, johngmyers commented on docs/bastion.md
> +# then you can SSH into control planes or worker nodes in the cluster, using the forwarded auth key
```suggestion
# then you can use the fowarded authentication to SSH into control-plane or worker nodes in the cluster.
```

2023-07-18 14:24 UTC, hakman commented
@techieforfun Could you also squash the commits? Thanks!

2023-07-18 14:52 UTC, techieforfun commented
it's ready @hakman

2023-07-18 15:02 UTC, hakman commented
Thanks @techieforfun!
/lgtm
/hold cancel

2023-07-18 15:14 UTC, johngmyers commented
/retest

2023-07-18 15:39 UTC, merged