Add missing security groups for cilium etcd
kubernetes/kops pull request #15766
Opened 2023-08-10 18:54 UTC by zadjadr

Fixes #15765

2023-08-11 01:57 UTC, hakman requested changes

2023-08-11 01:57 UTC, hakman commented on pkg/model/openstackmodel/firewall.go
>  	b.addDirectionalGroupRule(c, masterSG, masterSG, etcdPeerRule)
Please move the block after these 2 lines.

2023-08-11 01:57 UTC, hakman commented on pkg/model/openstackmodel/firewall.go
> +		if b.Cluster.Spec.Networking.Cilium.EtcdManaged {
```suggestion
	if b.Cluster.Spec.Networking.Cilium != nil && b.Cluster.Spec.Networking.Cilium.EtcdManaged {
```

2023-08-11 01:58 UTC, hakman commented
/cc @olemarkus 
/assign @zetaab

2023-08-11 08:57 UTC, olemarkus commented
Approach and rules looks good to me.

2023-08-11 10:15 UTC, zadjadr commented
Seems like I missing that 4003 from workers to master was also needed.
The cilium-agent pods on the workers would complain:

```
cilium-agent level=error msg="Unable to initialize local node. Retrying..." error="timeout while retrieving initial list of objects from kvstore" subsys=nodediscovery
```

2023-08-11 10:52 UTC, hakman commented
/ok-to-test

2023-08-11 11:47 UTC, zadjadr commented
Sorry, this should be the final addition.. When creating a new cluster, etcd tries to also check port 3992 (Master to Master)

2023-08-12 09:42 UTC, hakman approved these changes

2023-08-12 13:00 UTC, hakman commented
/retest

2023-08-12 13:43 UTC, merged