Create clusters with bigger default subnets
kubernetes/kops pull request #15791
Opened 2023-08-17 02:46 UTC by hakman

When creating a cluster, the network CIRD is split into 8 subnets.
For AWS, the network CIDR is at max a /16, which results in /19 subnets. This is quite small for AWS VPC CNI.

This PR proposes to split the network CIDR into bigger subnets, when the number of subnets allows it.

This only affects AWS and OpenStack:
https://github.com/kubernetes/kops/blob/73159cd6f50f72e004d972ce2ade21dcf40b7860/upup/pkg/fi/cloudup/defaults.go#L122-L128

/cc @johngmyers @justinsb @zetaab

2023-08-17 02:46 UTC, hakman commented
/hold for feedback
/cc @dims

2023-08-17 02:59 UTC, hakman commented
/test pull-kops-e2e-cni-amazonvpc

2023-08-17 03:56 UTC, hakman commented
/test pull-kops-e2e-cni-amazonvpc

2023-08-17 04:57 UTC, hakman commented
/test pull-kops-e2e-cni-amazonvpc

2023-08-17 05:04 UTC, zetaab commented
one thing that in my opinion we should keep in mind: there should be free space in VPC if for instance someone wants to migrate from availability zone a to availability zone b. It means that new subnets needs to be created before the old ones are removed. I have seen need for this in two different clusters during my kops usage.

In case of openstack I do not see huge issue with this, people can anyway change the behaviour with config if needed. I am more worried about default configuration for AWS.

2023-08-17 05:12 UTC, hakman commented
> one thing that in my opinion we should keep in mind: there should be free space in VPC if for instance someone wants to migrate from availability zone a to availability zone b. It means that new subnets needs to be created before the old ones are removed. I have seen need for this in two different clusters during my kops usage.

There is still room left with this approach. The first subnet CIRD is not allocated for cluster subnets, only for utility ones. It should be good enough for such migrations.

2023-08-17 10:29 UTC, dims commented
cc @jayanthvn @jdn5126

2023-08-19 23:50 UTC, johngmyers commented on pkg/apis/kops/validation/validation.go
> +		if subnet.Overlap(subnetCIDR, podCIDR) && c.Networking.AmazonVPC == nil {
I believe Cilium in ENI mode is in the same situation.

I wonder if the correct behavior for ENI-based CNIs is to leave `podCIDR` unset, like we do for IPv6. CCM is not assigning the pod IPs, the CNI is, deriving it from the ENI.

2023-08-20 00:03 UTC, johngmyers requested changes
Consider doing the same thing when splitting the little subnets.

2023-08-20 04:33 UTC, johngmyers approved these changes

2023-08-21 03:24 UTC, hakman commented
/hold cancel

2023-08-21 04:12 UTC, hakman commented
/retest

2023-08-21 04:57 UTC, merged