scaleway: rolling-update feature
kubernetes/kops pull request #15835
Opened 2023-08-29 15:49 UTC by Mia-Cross

This PR adds the possibility to edit the image and the size of the instances on a live cluster by performing a rolling-update.

This feature will also be useful for the Terraform support that's coming up next.

2023-08-29 16:46 UTC, hakman commented
/ok-to-test

2023-08-29 20:17 UTC, johngmyers requested changes

2023-08-29 20:17 UTC, johngmyers commented on upup/pkg/fi/cloudup/scalewaytasks/instance.go
> +		return false, fmt.Errorf("error getting actual user-data: %w", err)
Error messages shouldn't start with the word "error", as they're printed with an "error: " prefix.

2023-08-31 03:24 UTC, hakman approved these changes
Looking forward to Terraform output. 👍

2023-08-31 03:26 UTC, merged