[WIP] Allow disabling metadata-proxy
kubernetes/kops pull request #15885
Opened 2023-09-07 16:59 UTC by upodroid

/cc @justinsb 

I still need fix codegen and the docs

2023-09-08 03:27 UTC, johngmyers commented on pkg/apis/kops/cluster.go
> +	// MetadataProxy is the config for the metadata-proxy
```suggestion
	// MetadataProxy is the config for the metadata-proxy.
```

2023-09-08 03:27 UTC, johngmyers commented on pkg/model/components/gcpmetadataproxy.go
> +Copyright 2020 The Kubernetes Authors.
```suggestion
Copyright 2023 The Kubernetes Authors.
```

2023-09-08 03:27 UTC, johngmyers commented on upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go
> +	if b.Cluster.Spec.CloudProvider.GCE != nil && b.Cluster.Spec.CloudProvider.GCE.MetadataProxy != nil && fi.ValueOf(b.Cluster.Spec.CloudProvider.GCE.MetadataProxy.Enabled) {
MetadataProxy is guaranteed to be non-`nil` at this point. But if it were `nil` then the proxy would be enabled.

Same for MetadataProxy.Enabled.

2023-09-08 16:54 UTC, upodroid commented
Changing the PR to remove the feature entirely as discussed during the office hours. GCP deprecated this [product](https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata#concealment) a long time ago from GKE and the source code for it isn't around.

2023-09-08 18:17 UTC, johngmyers commented
The Office Hours decision was to remove it as of Kubernetes 1.29. If the Kubernetes version is 1.28 or earlier then it should still be installed.

Do we need to add any code to get it removed upon upgrade over the 1.29 boundary?

2023-09-08 21:14 UTC, upodroid commented
Fixed

2023-09-08 22:24 UTC, upodroid commented
/test pull-kops-e2e-k8s-gce-ci

2023-09-08 22:47 UTC, upodroid commented
Verified the changes in the `pull-kops-e2e-k8s-gce-ci` job which is testing against 1.29

2023-09-09 00:03 UTC, upodroid commented
/retest

2023-09-09 00:52 UTC, johngmyers commented
/retest
/lgtm

2023-09-09 01:01 UTC, upodroid commented
These jobs should have focus_regex to Conformance

2023-09-09 07:14 UTC, hakman requested changes

2023-09-09 07:14 UTC, hakman commented on docs/releases/1.28-NOTES.md
> +* We no longer deploy [metadata-proxy](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/metadata-proxy) on GCE clusters for K8s versions higher than 1.28. The proxy used to run as
```suggestion
* [metadata-proxy](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/metadata-proxy) is no longer deployed on GCP clusters for Kubernetes 1.28+.
```

2023-09-09 07:17 UTC, hakman commented
> These jobs should have focus_regex to Conformance

We can debate this at the next kOps Office Hours. 😆

2023-09-09 07:17 UTC, hakman commented
/lgtm

2023-09-09 07:17 UTC, hakman commented
/test pull-kops-e2e-k8s-gce-ci

2023-09-09 14:51 UTC, upodroid commented
I'm seeing infra bugs

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/15885/pull-kops-e2e-k8s-gce-ci/1700408126739582976/build-log.txt

my-hostname-private-cc309a20-27eb-4138-8dd2-b86c8864d452-j7pjv

<img width="1505" alt="image" src="https://github.com/kubernetes/kops/assets/25100905/7a7f4afb-a26b-4522-a772-fbc2aaeac73c">

2023-09-09 15:19 UTC, upodroid commented
Fixed the docs

2023-09-09 15:20 UTC, hakman approved these changes

2023-09-09 16:08 UTC, merged