aws: Attach security group to NLBs for kops-controller
kubernetes/kops pull request #16006
Opened 2023-10-07 12:58 UTC by hakman

This was broken in #15993

/cc @johngmyers @rifelpet

2023-10-07 12:59 UTC, hakman commented
/test pull-kops-e2e-aws-dns-none

2023-10-07 14:44 UTC, hakman commented
/test pull-kops-e2e-aws-dns-none

2023-10-07 15:13 UTC, hakman commented
/test pull-kops-e2e-aws-dns-none

2023-10-07 20:58 UTC, johngmyers commented
I think we want to add port 3988 to the appropriate list in AWSModelContext.GetSecurityGroups()

2023-10-07 23:58 UTC, hakman commented
> I think we want to add port 3988 to the appropriate list in AWSModelContext.GetSecurityGroups()

Done

2023-10-08 02:09 UTC, johngmyers requested changes

2023-10-08 02:09 UTC, johngmyers commented on pkg/model/awsmodel/api_loadbalancer.go
> +					Name:          fi.PtrTo(fmt.Sprintf("kops-controller-elb-to-master%s", suffix)),
```suggestion
					Name:          fi.PtrTo(fmt.Sprintf("kops-controller-elb-to-cp%s", suffix)),
```

2023-10-08 07:09 UTC, hakman commented
/retest
/test pull-kops-e2e-aws-dns-none

2023-10-08 08:49 UTC, hakman commented
/retest

2023-10-08 10:45 UTC, hakman commented
/retest

2023-10-08 16:28 UTC, hakman commented
/cc @upodroid

2023-10-08 16:40 UTC, upodroid approved these changes
LGTM

2023-10-08 16:41 UTC, hakman commented
/approve

2023-10-08 16:45 UTC, merged