If specified, posts event data to URL upon instance interruption action.
kubernetes/kops pull request #16009
Opened 2023-10-10 13:50 UTC by voriol

New try for fixe: https://github.com/kubernetes/kops/issues/14561

2023-10-10 14:18 UTC, hakman commented
> Adding label `do-not-merge/contains-merge-commits` because PR contains merge commits, which are not allowed in this repository. Use `git rebase` to reapply your commits on top of the target branch. Detailed instructions for doing so can be found [here](https://git.k8s.io/community/contributors/guide/github-workflow.md#4-keep-your-branch-in-sync).

@voriol Please rebase.

2023-10-10 15:54 UTC, hakman commented
@voriol See commit https://github.com/kubernetes/kops/pull/16009/commits/9b479b7ed811cbd3b2515c0767c2f96c6324b1b0 in https://github.com/kubernetes/kops/pull/16009/commits.

2023-10-11 07:07 UTC, hakman commented
/ok-to-test

2023-10-11 07:40 UTC, voriol commented
/retest

2023-10-11 09:41 UTC, voriol commented
I have reviewed the test output and I can't quite see where the problem is, I think it's not related to my changes. Can you help me please?

Thank you

2023-10-11 10:18 UTC, hakman requested changes

2023-10-11 10:19 UTC, hakman commented
> have reviewed the test output and I can't quite see where the problem is, I think it's not related to my changes.

It's probably a flake, please ignore for now.

2023-10-11 10:26 UTC, voriol commented on docs/releases/1.28-NOTES.md
> +
moved! thanks

2023-10-17 07:12 UTC, voriol commented
Hello @hakman , 

Is there any pending task on my part or is it pending your review?

Thank you

2023-10-17 08:43 UTC, hakman commented
Hey @voriol, I will try to take a look this week, sorry for the delay.

2024-02-13 11:37 UTC, voriol commented
Hello @hakman,

What do you want to do with this topic? Do we close it or continue it?

Thank You

2024-02-13 12:31 UTC, hakman commented
/retest

2024-02-13 13:29 UTC, merged