Improve kops edit command
kubernetes/kops pull request #16109
Opened 2023-11-18 10:25 UTC by prashantrewar

Fixes #16104

2023-11-22 05:20 UTC, hakman commented
/ok-to-test

2023-11-22 05:25 UTC, hakman commented
Hi @prashantrewar, this change should be done in https://github.com/kubernetes/kops/blob/master/cmd/kops/edit_cluster.go.
Docs are updated by running `make gen-cli-docs`.

2023-11-23 15:49 UTC, prashantrewar commented
Thank you @hakman. I have made the changes.

2023-11-23 17:17 UTC, hakman requested changes

2023-11-23 17:17 UTC, hakman commented on cmd/kops/edit_cluster.go
> +	# Set Values in the spec.
```suggestion
	# Set cluster spec values.
```

2023-11-23 17:17 UTC, hakman commented on docs/cli/kops_edit_cluster.md
> +  # Set Values in the spec.
```suggestion
  # Set cluster spec values.
```

2023-11-23 17:41 UTC, hakman commented
Thanks @prashantrewar! :)
/lgtm
/approve

2023-11-23 18:12 UTC, merged