aws: fix maxPods when cilium ipam=eni is used
kubernetes/kops pull request #16253
Opened 2024-01-15 15:24 UTC by argusua

**What does this PR introduce?**
This PR addresses the issue where kubelet is configured with maxPods 100 in the AWS environment and when cilium with ipam=eni is used.

**Why is this change needed?**
The number of IP addresses is connected to the AWS instance type and is much less than 100 which is the default maxPods value. So, for small instance types we in most cases end up with the pod not being able to schedule because of 'No IP's left to assign on aws instances'

**How does it address the issue?**
We use the same code to determine maxPods per AWS instance type as for amazonvpc networking.

**Related Issue**
Fixes https://github.com/kubernetes/kops/issues/16064

2024-01-15 18:15 UTC, hakman commented
Hi @argusua. Thanks for taking the time to submit a PR.
Please sign the CLA to be able to accept it.

2024-01-16 10:04 UTC, argusua commented
> Hi @argusua. Thanks for taking the time to submit a PR. Please sign the CLA to be able to accept it.

Done.

2024-01-16 10:26 UTC, hakman commented
/ok-to-test

2024-01-17 10:30 UTC, argusua commented
Can someone help with failed tests? Because for me it's not clear why they are failing. I've tried building and running nodeup on my test cluster with amazonvpc and cilium cni and it works correctly.

2024-01-17 11:09 UTC, hakman requested changes

2024-01-17 11:09 UTC, hakman commented on nodeup/pkg/model/kubelet.go
> +	if (b.NodeupConfig.Networking.AmazonVPC != nil || b.NodeupConfig.Networking.Cilium.IPAM == kops.CiliumIpamEni) && c.MaxPods == nil {
Probably this is why tests are failing.
```suggestion
	if (b.NodeupConfig.Networking.AmazonVPC != nil || (b.NodeupConfig.Networking.Cilium != nil && b.NodeupConfig.Networking.Cilium.IPAM == kops.CiliumIpamEni)) && c.MaxPods == nil {
```

2024-01-17 11:49 UTC, argusua commented
Thanks, @hakman It was also my thought but not clear why I can't recreate this on my local cluster. Anyway, I've commited your suggestion. Let's if this helps.

2024-01-17 11:57 UTC, argusua commented
/retest-required

2024-01-17 11:59 UTC, argusua commented
/test pull-kops-e2e-k8s-aws-calico

2024-01-17 13:01 UTC, argusua commented
Hi, @hakman Was able to recreate the issue locally too, and your suggestion fixed it. Also, looks like tests here is green now. Thanks.

2024-01-17 14:17 UTC, argusua commented
Hi, @hakman 
Done

2024-01-17 14:22 UTC, hakman approved these changes

2024-01-17 15:15 UTC, merged