Generate revisions of NLB objects, and introduce cleanup phase
kubernetes/kops pull request #16356
Opened 2024-02-15 15:37 UTC by justinsb

This lets us safely make changes to otherwise immutable fields, in
particular for adding security groups to NLBs created without them.

We detect the older versions, and create deletion tasks to remove
them.  These tasks can be deferred, and we expect them to be
deferred to a "prune" phase that runs after cluster apply.

2024-02-15 15:38 UTC, justinsb commented
This is the remaining work from #16291; I think it makes sense to consider as a single PR.  (I sent a new PR to keep the PR history understandable, even though they should now be the same!)

cc @hakman @rifelpet

2024-02-15 15:40 UTC, justinsb commented
One possible thing I've realized I could do ... I could split out the deletion tasks/printing/processing into a separate PR, and then only really use them in this PR.  That would make this one smaller... let me know!

2024-02-17 10:43 UTC, hakman commented
/test pull-kops-e2e-k8s-aws-calico

2024-02-17 12:48 UTC, hakman requested changes

2024-02-17 12:48 UTC, hakman commented on cmd/kops/update_cluster.go
> +	cmd.Flags().BoolVar(&options.DoDeferredDeletions, "cleanup-after-upgrade", options.DoDeferredDeletions, "Delete old revisions of cloud resources that were needed during an upgrade")
Do we want to use `prune` instead?
```suggestion
	cmd.Flags().BoolVar(&options.DoDeferredDeletions, "prune", options.DoDeferredDeletions, "Delete old revisions of cloud resources that were needed during an upgrade")
```

2024-02-17 14:01 UTC, justinsb commented on cmd/kops/update_cluster.go
> +	cmd.Flags().BoolVar(&options.DoDeferredDeletions, "cleanup-after-upgrade", options.DoDeferredDeletions, "Delete old revisions of cloud resources that were needed during an upgrade")
I like prune, let me make the change!

2024-02-17 16:41 UTC, justinsb commented
Changed to --prune, added a few more comments, and squashed the commits.

2024-02-17 18:18 UTC, hakman approved these changes

2024-02-17 19:17 UTC, merged