fix: Detect resolv.conf being a symlink, rather than relying on distro detection
kubernetes/kops pull request #16479
Opened 2024-04-20 17:12 UTC by justinsb

Distro detection is less reliable than understanding the actual
configuration in use, and with Debian 12 multiple configurations are
(more) probable.

2024-04-20 17:15 UTC, justinsb commented
cc @hakman 

This is the code I had written before that may be related to the issue brought up in office hours with debian12 on hetzner.  I will test debian12 on a few places.

It was "stuck" behind a more complicated PR, AFAICT ... sorry!

2024-04-20 21:27 UTC, justinsb commented
I validated the problem on debian12 on hetzner (we aren't running systemd-resolved there), and I updated the PR to fix it.  Essentially we want to strictly detect systemd-resolved, which is the problem.  kubelet can read /etc/resolv.conf even if it's a symlink, the issue only arises if /etc/resolv.conf includes 127.0.0.53 or something like that, which doesn't work in a container.

Another approach could be to look at /etc/resolv.conf for a `nameserver 127.0.0.x` line (or a similar approach), but that feels tricky  - we still have to find the "real" resolv.conf file (the one without proxies that only work in the host network-namespace).

2024-04-21 03:28 UTC, hakman commented
This is nice. We also have the `resolv-conf` flag override if needed in some distro:
https://github.com/kubernetes/kops/blob/47b12ba8410e0d35e77d2b2fee1ee9675c033866/pkg/apis/kops/componentconfig.go#L114-L115

2024-04-21 15:14 UTC, hakman requested changes

2024-04-21 15:14 UTC, hakman commented on util/pkg/distributions/distributions.go
> +func (d *Distribution) HasLoopbackEtcResolvConf() (string, bool) {
Do we still need the bool, could just return a string ptr or `nil`.
```suggestion
func (d *Distribution) HasLoopbackEtcResolvConf() *string {
```

2024-04-21 15:15 UTC, hakman commented on util/pkg/distributions/distributions.go
> +func (d *Distribution) HasLoopbackEtcResolvConf() (string, bool) {
Seems like a minor nuisance.

2024-04-21 15:15 UTC, hakman commented
/lgtm
/approve

2024-04-22 00:03 UTC, rifelpet commented
/lgtm cancel

for test failure

2024-05-07 07:09 UTC, hakman commented
I think https://github.com/kubernetes/kops/pull/16495 will fix the problem for now, as discussed during Office Hours.
Let's revisit this if the issue reappears.
/close

2024-05-07 07:09 UTC, closed without merging