Upgrade node-termination-handler to 1.21.0
kubernetes/kops pull request #16572
Opened 2024-05-15 10:56 UTC by jim-barber-he

Also allow to specify the following extra parameters for it.
- deleteSqsMsgIfNodeNotFound
- memoryLimit
- podTerminationGracePeriod
- taintNode
- webhookTemplate

2024-05-15 10:59 UTC, jim-barber-he commented
I've created 2 commits so that you can see my changes in the first one, then the 2nd one has 209 test files updated from running `hack/update-expected.sh`
I'm happy to squash these commits together and force push at the end if you like.

2024-05-15 23:30 UTC, jim-barber-he commented
Node Termination Handler v1.22.0 was released a moment ago.
https://github.com/aws/aws-node-termination-handler/releases/tag/v1.22.0

There are no changes to the helm charts apart from bumping the version, so I man as well change this to use it.

2024-05-16 03:07 UTC, hakman commented
/ok-to-test

2024-05-16 04:32 UTC, hakman requested changes

2024-05-16 04:32 UTC, hakman commented on pkg/apis/kops/componentconfig.go
> +	DeleteSqsMsgIfNodeNotFound *bool `json:"deleteSqsMsgIfNodeNotFound,omitempty"`
SQS should be in uppercase.
```suggestion
	DeleteSQSMsgIfNodeNotFound *bool `json:"deleteSQSMsgIfNodeNotFound,omitempty"`
```

2024-05-16 04:51 UTC, jim-barber-he commented on pkg/apis/kops/componentconfig.go
> +	DeleteSqsMsgIfNodeNotFound *bool `json:"deleteSqsMsgIfNodeNotFound,omitempty"`
Done.

2024-05-16 04:53 UTC, hakman approved these changes
Thanks @jim-barber-he! 👍

2024-05-16 05:03 UTC, jim-barber-he commented
Do you need/want the 2x commits squashed into 1?

2024-05-16 05:28 UTC, hakman commented
> Do you need/want the 2x commits squashed into 1?

Nop, all good. Thanks!

2024-05-16 05:47 UTC, merged

2024-05-30 03:58 UTC, jim-barber-he commented
@hakman Will this be in the next kops 1.29 release?
If not planned, are you okay if I raise a PR to cherry-pick it into 1.29?

2024-05-30 10:26 UTC, hakman commented
@jim-barber-he Sure, I don't see any issue with that. Thanks!

2024-05-31 01:40 UTC, jim-barber-he commented
Thank @hakman
The PR is here:
https://github.com/kubernetes/kops/pull/16595