Add support for using ECR as pull-through image cache
kubernetes/kops pull request #16593
Opened 2024-05-30 12:51 UTC by rsafonseca

This PR introduces a simple way to enable using ECR as a Pull-through image cache, without having to mutate images on the cluster using tools like Kyverno.

Containerd already has support for specifying registry mirrors in kops, but since ECR uses short lived tokens, it's not trivial (or even impossible without adding a few extra hacks on top of it) to use it as a pull-through cache.

This PR also bumps the ecr-credential-provider binary, which before version 1.29.0 specifically tried to parse an ECR repo from the image passed, leading to not being possible to enable this feature. This is now resolved in the latest versions.

This PR uses a flag to enable the feature when needed, and adds any server addresses configured in the mirrors to be allowed on the CredentialProviderConfig object that kops configures on the kubelet.

2024-05-30 16:54 UTC, hakman commented
/ok-to-test

2024-05-30 18:04 UTC, rsafonseca commented
/retest

2024-05-30 20:11 UTC, rsafonseca commented
Any idea why these e2e tests might be failing @hakman?
It seems odd that they never come up and the log dump references not finding an unrelated role that should belong to another job
e.g.
pull-kops-e2e-cni-amazonvpc:
```
0530 19:12:47.346328   14816 dumplogs.go:51] /home/prow/go/src/k8s.io/kops/.build/dist/linux/amd64/kops toolbox dump --name e2e-pr16593.pull-kops-e2e-cni-amazonvpc.test-cncf-aws.k8s.io --dir /logs/artifacts --private-key /tmp/kops/e2e-pr16593.pull-kops-e2e-cni-amazonvpc.test-cncf-aws.k8s.io/id_ed25519 --ssh-user ubuntu
W0530 19:12:59.466784   50124 aws.go:2055] could not find role "masters.e2e-pr16593.pull-kops-e2e-cni-cilium-ipv6.test-cn-40qra0". Resource may already have been deleted: operation error IAM: GetInstanceProfile, https response error StatusCode: 404, RequestID: 013035b7-7eba-43a9-98dd-abf842145433, NoSuchEntity: Instance Profile masters.e2e-pr16593.pull-kops-e2e-cni-cilium-ipv6.test-cn-40qra0 cannot be found.
W0530 19:13:02.485316   50124 aws.go:2055] could not find role "nodes.e2e-pr16593.pull-kops-e2e-cni-cilium-ipv6.test-cncf-47o1f8". Resource may already have been deleted: operation error IAM: GetInstanceProfile, https response error StatusCode: 404, RequestID: 4bc7f2c4-9c38-4723-85bd-b493cf0794c8, NoSuchEntity: Instance Profile nodes.e2e-pr16593.pull-kops-e2e-cni-cilium-ipv6.test-cncf-47o1f8 cannot be found.
```
could something be leaking somewhere? or do you think there's any change here that could be somehow related to this weird behaviour?

2024-05-31 07:55 UTC, rsafonseca commented
/retest

2024-05-31 08:20 UTC, hakman commented
Please ignore the IPv6 tests

2024-05-31 10:02 UTC, rsafonseca commented
All good then, though it looks like pull-kops-e2e-cni-cilium-eni is flaky, passed on retest.
Any thoughts on this PR @hakman ? Does it make sense to you to add the config option under containerd on the CRD? :)

2024-06-10 12:15 UTC, rsafonseca commented
/retest-required

2024-06-10 20:28 UTC, rsafonseca commented
/retest-required

2024-06-21 08:38 UTC, sczelo commented
Any update about this PR? Do you need any help or test, to be merged faster?
I built the images locally from this repo and tested it on AWS. It's worked for me.

2024-06-21 19:44 UTC, rsafonseca commented
Did you get a chance to review this yet @hakman @johngmyers ? :)

2024-07-02 12:08 UTC, SzilardS commented
@rifelpet @hakman @johngmyers is there any way we can help you guys to get it merged before/into the 1.30 release?

2024-07-06 17:39 UTC, rsafonseca commented
/retest-required

2024-09-02 23:17 UTC, elliotdobson commented
> This PR also bumps the ecr-credential-provider binary, which before version 1.29.0 specifically tried to parse an ECR repo URL from the image passed, leading to not being possible to enable this feature. This is now resolved in the latest versions.

@rsafonseca can you provide some more details about this? An issue or PR from the source repo?

2024-09-03 12:08 UTC, rsafonseca commented
There is no specific issue regarding this, simply the failure logic was changed some commits ago to not error out when it fails to parse an ECR specific url. This is easy to test with the old vs newer binaries, the version that kops currently has in the assets will drop out and not pass the ecr auth token when the referenced image repo is not ECR, so when containerd tries to use ECR as a mirror it has no creds.

2024-09-26 09:43 UTC, rsafonseca commented
Hey folks, can anyone take a look at this? :)

2024-10-24 17:21 UTC, rsafonseca commented
/retest-required

2024-10-24 21:45 UTC, rsafonseca commented
/test pull-kops-e2e-cni-flannel

2024-10-24 21:45 UTC, rsafonseca commented
/test pull-kops-e2e-cni-cilium-eni

2024-10-25 13:28 UTC, rsafonseca commented
/retest-required

2024-11-01 16:37 UTC, justinsb commented on nodeup/pkg/model/kubelet.go
> +`
In office hours, we talked about whether UseECRCredentialsForMirrors should be per mirror or whether we only apply this to urls that "look like" ECR.  The (compelling) argument that @rsafonseca made is that people aren't likely to have multiple mirrors so it's not necessary.

👍

2024-11-04 18:18 UTC, rsafonseca commented
@hakman I've removed the for loop from the inline string literal as you had suggested in the office hours, and in fact i removed the whole string literal. Overall the number of lines increased, but it should be more readable and easier to manipulate in the future. https://github.com/kubernetes/kops/pull/16593/commits/2852bccdbee7291a8a5a2bc4e32f2a83a88a525b

2025-04-22 07:06 UTC, itskingori commented
/remove-lifecycle stale

2025-07-10 19:35 UTC, rsafonseca commented
rebased again, the number of files that needed their hashes updated inside tests/integration increased dramatically since the last rebase so the bot just moved this from L to XXL 🫠

2025-07-11 07:01 UTC, hakman commented on pkg/nodemodel/fileassets.go
> +					binaryLocation = fi.PtrTo("https://artifacts.k8s.io/binaries/cloud-provider-aws/v1.29.0")
Please remove this from the PR.  Will be done as part of https://github.com/kubernetes/kops/pull/17486.

2025-07-11 08:54 UTC, rsafonseca commented on pkg/nodemodel/fileassets.go
> +					binaryLocation = fi.PtrTo("https://artifacts.k8s.io/binaries/cloud-provider-aws/v1.29.0")
cool, i'll remove and rebase as soon as you merge #17486 as this PR won't work with v1.27.1 (it was only tested with 1.29, but hopefully no breaking changes in 1.31)

2025-07-11 15:38 UTC, rsafonseca commented on pkg/nodemodel/fileassets.go
> +					binaryLocation = fi.PtrTo("https://artifacts.k8s.io/binaries/cloud-provider-aws/v1.29.0")
done

2025-07-11 17:08 UTC, hakman requested changes

2025-07-11 17:08 UTC, hakman commented on pkg/model/iam/iam_builder.go
> +		"ecr:TagResource",
@rsafonseca Please move these to a separate `addECRPullThroughPermissions(p *Policy)` function and call it only when the flag is set.

2025-07-11 17:48 UTC, hakman commented on pkg/model/iam/iam_builder.go
> +		"ecr:TagResource",
Also, add the new option to this test, to see how the generated output looks like. Other than these, LGTM.
https://github.com/kubernetes/kops/blob/93d0bed9ae9fa26b7cc3f6115a5d4c017515b0ec/tests/integration/update_cluster/containerd-custom/in-v1alpha2.yaml#L13-L22

2025-07-27 05:07 UTC, hakman commented on pkg/model/iam/iam_builder.go
> +		"ecr:TagResource",
Kind ping on this @rsafonseca. Let me know if you have any feedback here.

2025-07-28 10:20 UTC, rsafonseca commented on pkg/model/iam/iam_builder.go
> +		"ecr:TagResource",
oops, sorry i missed your comment earlier, sorting this out now as requested :)

2025-07-28 10:32 UTC, rsafonseca commented on pkg/model/iam/iam_builder.go
> +		"ecr:TagResource",
all done @hakman 👍

2025-07-28 10:41 UTC, hakman commented on pkg/model/iam/iam_builder.go
> +		"ecr:TagResource",
Thanks, looks good to merge. One final squash, please.

2025-07-28 11:03 UTC, hakman commented
The tests are broken, so please ignore for now. Will fix them and merge this.

2025-07-28 11:03 UTC, hakman commented
/lgtm

2025-07-28 11:03 UTC, hakman commented
/hold for tests to be fixed

2025-07-28 11:47 UTC, rsafonseca commented on pkg/model/iam/iam_builder.go
> +		"ecr:TagResource",
done :)

2025-07-28 12:13 UTC, hakman commented
/lgtm

2025-07-29 09:53 UTC, hakman commented
/unhold
/retest

2025-07-29 09:53 UTC, hakman commented
/test all

2025-07-29 09:55 UTC, hakman commented
/approve

2025-07-29 10:13 UTC, hakman commented
/retest

2025-07-29 10:56 UTC, hakman commented
/override pull-kops-e2e-cni-amazonvpc

2025-07-29 10:56 UTC, hakman commented
/override pull-kops-e2e-k8s-gce-ipalias

2025-07-29 11:00 UTC, hakman commented
/override pull-kops-e2e-cni-cilium-eni

2025-07-29 11:02 UTC, merged

2025-10-30 04:58 UTC, jim-barber-he commented on nodeup/pkg/model/kubelet.go
> +`
Is this still the case?

Unfortunately ECR pull-through only supports specific registries.
I have 4 other registries that I'd like to handle with harbor, while using ECR for the ones it supports.