Update API slice fields to not use pointers
kubernetes/kops pull request #9802
Opened 2020-08-23 22:41 UTC by rifelpet

A slice of pointers causes problems with the Kubernetes 1.19 code-generator.

A nil entry in these slices isn't valid anyways, so this should have no impact short of being a breaking change for anyone importing these API types.

2020-08-23 23:03 UTC, rifelpet commented
/hold for comment

2020-08-23 23:57 UTC, johngmyers commented
/lgtm

2020-08-24 02:20 UTC, rifelpet commented
/test pull-kops-e2e-k8s-containerd

2020-08-24 03:02 UTC, rifelpet commented
/test pull-kops-e2e-k8s-containerd

2020-08-24 03:23 UTC, rifelpet commented
/test pull-kops-e2e-k8s-containerd

2020-08-24 03:36 UTC, rifelpet commented
/test pull-kops-e2e-k8s-containerd

2020-08-24 03:58 UTC, rifelpet commented
/test pull-kops-e2e-k8s-containerd

2020-08-24 04:40 UTC, olemarkus commented
/lgtm

2020-08-24 05:53 UTC, hakman requested changes
I think using a pointer to a slice member would reduce the number of changes.

2020-08-24 05:53 UTC, hakman commented on pkg/model/components/etcdmanager/options.go
> +		if etcdClusters[i].Provider != kops.EtcdProviderTypeManager {
```suggestion
	for i := range etcdClusters {
		etcdCluster := &etcdClusters[i]
		if etcdCluster.Provider != kops.EtcdProviderTypeManager {
```

2020-08-24 05:53 UTC, hakman commented on pkg/model/components/etcd.go
> +		if etcdClusters[i].Provider == "" {
```suggestion
	for i := range spec.EtcdClusters {
		c := &spec.EtcdClusters[i]
 		if c.Provider == "" {
```

2020-08-24 05:53 UTC, hakman commented on pkg/model/awsmodel/autoscalinggroup.go
> +			ig.Spec.Volumes[i].Type = DefaultVolumeType
```suggestion
		x := &ig.Spec.Volumes[i]
		if x.Type == "" {
 			x.Type = DefaultVolumeType
```

2020-08-24 09:57 UTC, hakman commented on upup/pkg/fi/cloudup/new_cluster.go
>  		}
This should not exist at all. Removing in https://github.com/kubernetes/kops/pull/9803.

2020-08-24 12:31 UTC, rifelpet commented
Updated to use pointers when modifying elements in a for loop. diff looks much cleaner now 👍 
I'll wait for #9803 to merge before rebasing once more. just to confirm the containerd e2e job still passes.

2020-08-24 12:48 UTC, rifelpet commented
/hold cancel
/test pull-kops-e2e-k8s-containerd

2020-08-24 12:50 UTC, hakman commented
/lgtm

2020-08-24 13:29 UTC, hakman commented
/test pull-kops-e2e-kubernetes-aws

2020-08-24 14:13 UTC, merged