Support ChainInsertMode config option for Calico Networking
kubernetes/kops pull request #9945
Opened 2020-09-15 15:17 UTC by asmith030

Add support for the ChainInsertMode configuration option when using Calico networking.

From https://docs.projectcalico.org/reference/felix/configuration:

Controls whether Felix hooks the kernel’s top-level iptables chains by inserting a rule at the top of the chain or by appending a rule at the bottom. Insert is the safe default since it prevents Calico’s rules from being bypassed. If you switch to Append mode, be sure that the other rules in the chains signal acceptance by falling through to the Calico rules, otherwise the Calico policy will be bypassed. [Default: Insert]

2020-09-15 15:40 UTC, KashifSaadat commented on upup/models/bindata.go
> +              value: "{{- or .Networking.Calico.ChainInsertMode "insert" }}"
There's a section further below ` # kops additions`, can you move it to there?

2020-09-16 01:40 UTC, rifelpet commented
/ok-to-test

2020-09-16 05:09 UTC, hakman requested changes
Please also add validation for the new option, similar to the Canal one. Other than that, looks good.
https://github.com/kubernetes/kops/blob/036ea6952554d86fd452f244127957beceb841c5/pkg/apis/kops/validation/validation.go#L657-L660

2020-09-16 09:48 UTC, KashifSaadat approved these changes
Thanks for the contribution @asmith030 !

/ok-to-test
/lgtm
/approve

2020-09-16 11:19 UTC, merged